version: "3.7"

services:
  myjenkins:
    build:
      context: .
    image: myjenkins
    ports:
     - "8080:8080"
    depends_on:
     - mysonar
     - artifactory
    links:
      - mysonar
      - artifactory
    volumes:
     - "./jobs:/var/jenkins_home/jobs/"
     - "./m2deps:/var/jenkins_home/.m2/repository/"
     - "./downloads:/var/jenkins_home/downloads"
    secrets:
     - jenkinsUsername
     - jenkinsPassword
     - artifactoryPassword
  mysonar:
    image: sonarqube:lts
    ports:
     - "9000"
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.7.0
    ports:
     - "8081"

secrets:
  jenkinsUsername:
    file: ./secrets/jenkinsUsername
  jenkinsPassword:
    file: ./secrets/jenkinsPassword
  artifactoryPassword:
    file: ./secrets/artifactoryPassword